title: API Generation ðŸ¤–
description: >-
  Generate dotnet APIs, mocks and clients from openapi specs.
url: "https://www.maisiesadler.co.uk/"
github_username: maisiesadler
author: Maisie Sadler
logo: ./images/logo.svg

remote_theme: pages-themes/slate@v0.2.0
plugins:
 - jekyll-feed
 - jekyll-remote-theme
